[package]
name = "ros"
version = "0.1.0"
authors = ["Nathan Kleyn <nathan@nathankleyn.com>"]

[dependencies]
rlibc = "1.0"
spin = "0.4.6"
volatile = "0.2.3"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]
